# Generated by Django 3.1.3 on 2020-11-24 08:39

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('seats', models.TextField(null=True)),
                ('doors', models.TextField(null=True)),
                ('transmission', models.CharField(choices=[('Manual', 'M'), ('Auto', 'A')], max_length=300, null=True)),
                ('fuel', models.CharField(choices=[('Petrol', 'P'), ('Diesel', 'D')], max_length=300, null=True)),
                ('car_type', models.CharField(choices=[('S', 'Sports Car'), ('M', 'Mid-size Vehicle'), ('L', 'Large Vehicle'), ('A', 'Ambulance')], max_length=300, null=True)),
                ('daily_rent', models.IntegerField()),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(help_text='Borrowed is on ..', null=True, verbose_name='Start Date')),
                ('returndate', models.DateField(help_text='will be returned on ...', null=True, verbose_name='Return Date')),
                ('cell_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookedcar', to='carhire.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
